### PR TITLE
Allow async time check

### PR DESCRIPTION
**Pull request by DmitryKuzmenko**
Adds an onptional ability to run each mirror test in a separate process
in parallel. This could possibly produce inaccurate results but speeds
up the process for a number of mirrors.

Signed-off-by: Dmitry Kuzmenko <dmitry.kuzmenko@dsr-corporation.com>

### CODE REVIEW

**Comment by archlinux-github** [comment]
This project is a read-only mirror of: https://gitlab.archlinux.org/archlinux/pacman-contrib, please submit your work there.

*This comment was generated by [github-pull-closer](https://gitlab.archlinux.org/archlinux/github-pull-closer).*

**Comment by kyrias** [comment]
Hey,

As registration for the Arch Linux GitLab instance has been closed I'll leave the review here anyway.

While I'm overall fine with this being feature implemented, you cannot have multiple background jobs writing to stdout at the same time as there's no synchronization between them, and so if two jobs try to write at the same time you can end up with  garbled output.

A better way to do it would be to use `parallel`.  This should be easy to do since `parallel` can execute Bash functions.  If you build up an array with all of the servers you should be able to just export the `get_url_time` function and then do something like `parallel get_url_time ::: "${servers[@]}"`

Also, I would prefer `-p`/`--parallel` rather than async.

**Comment by polyzen** [comment]
From IRC: "gitlab registrations are open again (since yesterday)".

**Comment by DmitryKuzmenko** [comment]
Thank you @kyrias, @polyzen! I will apply the change and create a merge request on Gitlab then.

**Pull request closed without merging**
